server.port=8091
spring.application.name=comentarios

spring.datasource.url=jdbc:mysql://localhost:3306/db_comentarios?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=pass1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.serviceUrl.defaultZone=http://26.87.230.97:8761/eureka
eureka.instance.preferIpAddress=true
eureka.instance.hostname=localhost
eureka.client.enabled=true